# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9eb05abd4b1cbaf52d45e8dc9035f555c71bd69fee38ddd87b1cdaf3aa389201206ab4d2b69f5a25795ccd5a78ce48f07a242104b27621bc8a6cdb31cbb861d1

test:
  secret_key_base: 7e5af795a8f295e18231794797b55dd8e6911835364ce85047636a6e22bb0692ce506c1a2e0ad05c9a0e26d69938b9fe8345b2c74825d1e69b1f4661bfe2deca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
